# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '.wtf'
tagline:          ''
description:      ''
url:              http://blog.address.wtf/
baseurl:          /

links:
  - title: GitHub
    icon: fa-github
    url: https://github.com/victor-pavlychko
  - title: Twitter
    icon: fa-twitter
    url: https://twitter.com/victorpavlychko
  - title: Facebook
    icon: fa-facebook
    url: https://www.facebook.com/victor.pavlychko
  - title: Instagam
    icon: fa-instagram
    url: https://instagram.com/victor.pavlychko
  # - title: LinkedIn
  #   icon: fa-linkedin
  #   url: https://linkedin.com/in/victorpavlychko

author:
  name:           'Victor Pavlychko'
  url:            http://address.wtf/

paginate:         5

