# Setup
url: http://hyde.getpoole.com
baseurl: /
title: Hyde
tagline: A Jekyll theme
description: >
  A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs
  a prominent sidebar with uncomplicated content.
  Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.

links:
  - title: Download
    icon: fa-download
    url: https://github.com/poole/hyde/archive/v2.1.0
  - title: GitHub project
    icon: fa-github
    url: https://github.com/poole/hyde
  - title: Twitter
    icon: fa-twitter
    url: https://twitter.com/mdo
  # - title: Facebook
  #   icon: fa-facebook
  #   url: https://www.facebook.com/
  # - title: Instagam
  #   icon: fa-instagram
  #   url: https://instagram.com/
  # - title: LinkedIn
  #   icon: fa-linkedin
  #   url: https://linkedin.com/

author:
  name: Mark Otto
  url: https://twitter.com/mdo

# Config
paginate: 5
paginate_path: page:num
permalink: pretty
excerpt_separator: <!-- more -->

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
